from extensions import db
from models import Product
from app import app

# Mock product data for diverse categories


mock_products = [
    {"name": "Wireless Headphones", "price": 59.99, "description": "Bluetooth headphones with noise-cancellation.", "category": "Electronics"},
    {"name": "Smartphone", "price": 699.99, "description": "Latest 5G smartphone with high-resolution display.", "category": "Electronics" },
    {"name": "Laptop Backpack", "price": 45.99, "description": "Durable backpack with multiple compartments.", "category": "Accessories" },
    {"name": "Gaming Mouse", "price": 29.99, "description": "Ergonomic mouse with customizable buttons.", "category": "Gaming" },
    {"name": "Electric Kettle", "price": 25.99, "description": "1.5L kettle with auto shut-off and boil-dry protection.", "category": "Home Appliances" },
    {"name": "Running Shoes", "price": 89.99, "description": "Lightweight shoes with excellent grip and comfort.", "category": "Footwear"  },
    {"name": "Smartwatch", "price": 199.99, "description": "Fitness tracking smartwatch with heart rate monitor.", "category": "Electronics" },
    {"name": "Desk Lamp", "price": 15.99, "description": "LED desk lamp with adjustable brightness.", "category": "Home" },
    {"name": "Yoga Mat", "price": 25.00, "description": "Non-slip yoga mat for home workouts.", "category": "Fitness"  },
    {"name": "T-Shirt", "price": 14.99, "description": "Cotton T-shirt available in various sizes.", "category": "Clothing" },
    {"name": "Bluetooth Speaker", "price": 49.99, "description": "Portable speaker with deep bass and clear sound.", "category": "Electronics" },
    {"name": "Wireless Charger", "price": 19.99, "description": "Fast wireless charging pad for smartphones.", "category": "Electronics" },
    {"name": "Fitness Tracker", "price": 39.99, "description": "Monitor your activity and sleep patterns.", "category": "Fitness"  },
    {"name": "Portable SSD", "price": 89.99, "description": "1TB portable SSD for fast data transfer.", "category": "Electronics" },
    {"name": "Coffee Maker", "price": 79.99, "description": "Brew your favorite coffee with ease.", "category": "Home Appliances"  },
    {"name": "Gaming Chair", "price": 199.99, "description": "Ergonomic chair designed for gamers.", "category": "Gaming"  },
    {"name": "Action Camera", "price": 299.99, "description": "Capture your adventures in high definition.", "category": "Electronics" },
    {"name": "Wireless Earbuds", "price": 89.99, "description": "Compact earbuds with great sound quality.", "category": "Electronics"  },
    {"name": "Smart Home Hub", "price": 99.99, "description": "Control all your smart devices from one place.", "category": "Home" },
    {"name": "Electric Toothbrush", "price": 49.99, "description": "Rechargeable toothbrush with multiple modes.", "category": "Health" },
    {"name": "Air Fryer", "price": 129.99, "description": "Cook healthier meals with less oil.", "category": "Home Appliances" },
    {"name": "Men's Sneakers", "price": 69.99, "description": "Stylish sneakers for everyday wear.", "category": "Footwear"},
    {"name": "Women's Running Shoes", "price": 89.99, "description": "Comfortable running shoes for women.", "category": "Footwear"},
    {"name": "Laptop Stand", "price": 29.99, "description": "Adjustable stand for better ergonomics.", "category": "Accessories"},
    {"name": "Wireless Keyboard", "price": 39.99, "description": "Sleek keyboard with a comfortable layout.", "category": "Electronics"},
    {"name": "Smart Light Bulb", "price": 19.99, "description": "Control your lighting with your smartphone.", "category": "Home"},
    {"name": "Portable Blender", "price": 29.99, "description": "Blend smoothies on the go.", "category": "Home Appliances"},
    {"name": "Yoga Block", "price": 15.99, "description": "Support for your yoga practice.", "category": "Fitness"},
    {"name": "Fitness Resistance Bands", "price": 24.99, "description": "Versatile bands for strength training.", "category": "Fitness"},
    {"name": "Men's Casual Shirt", "price": 34.99, "description": "Stylish shirt for casual outings.", "category": "Clothing"},
    {"name": "Women's Blouse", "price": 39.99, "description": "Elegant blouse for formal occasions.", "category": "Clothing"},
    {"name": "Children's Toy Set", "price": 49.99, "description": "Fun and educational toy set for kids.", "category": "Toys"},
    {"name": "Cookbook", "price": 19.99, "description": "Delicious recipes for every occasion.", "category": "Books"},
    {"name": "Wireless Gaming Headset", "price": 89.99, "description": "Immersive sound for gaming.", "category": "Gaming"},
    {"name": "Smart Thermostat", "price": 129.99, "description": "Control your home's temperature remotely.", "category": "Home"},
    {"name": "Pet Water Fountain", "price": 39.99, "description": "Keep your pets hydrated with fresh water.", "category": "Pets"},
    {"name": "Travel Pillow", "price": 19.99, "description": "Comfortable pillow for travel.", "category": "Accessories"},
    {"name": "Wall Art", "price": 59.99, "description": "Beautiful art piece to decorate your home.", "category": "Home"},
    {"name": "Bluetooth Headset", "price": 49.99, "description": "Hands-free headset for calls.", "category": "Electronics"},
    {"name": "Electric Grill", "price": 99.99, "description": "Grill your favorite foods indoors.", "category": "Home Appliances"},
    {"name": "Portable Phone Charger", "price": 29.99, "description": "Keep your devices charged on the go.", "category": "Electronics"},
    {"name": "Gardening Tools Set", "price": 39.99, "description": "Essential tools for gardening enthusiasts.", "category": "Home"},
    {"name": "Camping Tent", "price": 149.99, "description": "Durable tent for outdoor adventures.", "category": "Outdoor"},
    {"name": "Hiking Backpack", "price": 79.99, "description": "Spacious backpack for hiking trips.", "category": "Outdoor"},
    {"name": "Fitness Mat", "price": 29.99, "description": "Comfortable mat for workouts.", "category": "Fitness"},
    {"name": "Digital Camera", "price": 499.99, "description": "Capture stunning photos and videos.", "category": "Electronics"},
    {"name": "VR Headset", "price": 299.99, "description": "Experience virtual reality like never before.", "category": "Gaming"},
    {"name": "Electric Pressure Cooker", "price": 89.99, "description": "Cook meals quickly and easily.", "category": "Home Appliances"},
    {"name": "Smartphone Case", "price": 19.99, "description": "Protect your phone with style.", "category": "Accessories"},
    {"name": "Wireless Security Camera", "price": 129.99, "description": "Monitor your home from anywhere.", "category": "Home"},
    {"name": "Portable Air Conditioner", "price": 299.99, "description": "Stay cool during hot summer days.", "category": "Home Appliances"},
    {"name": "Electric Blanket", "price": 59.99, "description": "Stay warm and cozy during winter.", "category": "Home"},
    {"name": "Smart Scale", "price": 39.99, "description": "Track your weight and body composition.", "category": "Health"},
    {"name": "Men's Watch", "price": 149.99, "description": "Stylish watch for men.", "category": "Accessories"},
    {"name": "Women's Handbag", "price": 89.99, "description": "Fashionable handbag for women.", "category": "Accessories"},
    {"name": "Kids' Bicycle", "price": 199.99, "description": "Safe and fun bicycle for children.", "category": "Toys"},
    {"name": "Board Game", "price": 29.99, "description": "Fun board game for family game nights.", "category": "Toys"},
    {"name": "Puzzle", "price": 19.99, "description": "Challenging puzzle for all ages.", "category": "Toys"},
    {"name": "Smartphone Tripod", "price": 24.99, "description": "Stabilize your smartphone for perfect shots.", "category": "Accessories"},
    {"name": "Electric Scooter", "price": 399.99, "description": "Eco-friendly scooter for urban commuting.", "category": "Outdoor"},
    {"name": "Portable Speaker", "price": 69.99, "description": "Take your music anywhere with this portable speaker.", "category": "Electronics"},
    {"name": "Home Gym Set", "price": 199.99, "description": "Complete set for home workouts.", "category": "Fitness"},
    {"name": "Smartphone Gimbal", "price": 89.99, "description": "Stabilize your videos with this gimbal.", "category": "Accessories"},
    {"name": "Electric Wine Opener", "price": 39.99, "description": "Open your wine bottles effortlessly.", "category": "Home"},
    {"name": "LED Strip Lights", "price": 29.99, "description": "Colorful lights to enhance your space.", "category": "Home"},
    {"name": "Pet Bed", "price": 49.99, "description": "Comfortable bed for your furry friend.", "category": "Pets"},
    {"name": "Smart Pet Feeder", "price": 99.99, "description": "Automate feeding for your pets.", "category": "Pets"},
    {"name": "Digital Thermometer", "price": 19.99, "description": "Quick and accurate temperature readings.", "category": "Health"},
    {"name": "Electric Skillet", "price": 49.99, "description": "Versatile skillet for cooking a variety of meals.", "category": "Home Appliances"},
    {"name": "Wireless Game Controller", "price": 59.99, "description": "Enhance your gaming experience with this controller.", "category": "Gaming"},
    {"name": "Smartphone Lens Kit", "price": 29.99, "description": "Enhance your smartphone photography.", "category": "Accessories"},
    {"name": "Outdoor Grill", "price": 199.99, "description": "Perfect for barbecues and outdoor cooking.", "category": "Outdoor"},
    {"name": "Camping Stove", "price": 49.99, "description": "Compact stove for camping trips.", "category": "Outdoor"},
    {"name": "Water Bottle", "price": 14.99, "description": "Reusable water bottle for hydration on the go.", "category": "Accessories"},
    {"name": "Travel Backpack", "price": 69.99, "description": "Spacious and durable backpack for travel.", "category": "Accessories"},
    {"name": "Smartphone Holder", "price": 19.99, "description": "Securely hold your smartphone while driving.", "category": "Accessories"},
    {"name": "Electric Shaver", "price": 39.99, "description": "Get a smooth shave with this electric shaver.", "category": "Health"},
    {"name": "Portable Massage Gun", "price": 89.99, "description": "Relieve muscle tension with this massage gun.", "category": "Health"},
    {"name": "Home Security System", "price": 299.99, "description": "Keep your home safe with this security system.", "category": "Home"},
    {"name": "Smart Doorbell", "price": 129.99, "description": "See who’s at your door from your smartphone.", "category": "Home"},
    {"name": "Electric Pressure Washer", "price": 149.99, "description": "Clean your outdoor spaces with ease.", "category": "Home"},
    {"name": "Cordless Vacuum Cleaner", "price": 199.99, "description": "Effortlessly clean your home with this vacuum.", "category": "Home"},
    {"name": "Smart Refrigerator", "price": 999.99, "description": "Keep your food fresh with smart technology.", "category": "Home Appliances"},
    {"name": "Air Purifier", "price": 129.99, "description": "Breathe cleaner air with this purifier.", "category": "Home"},
    {"name": "Smart Coffee Maker", "price": 149.99, "description": "Brew coffee from your smartphone.", "category": "Home Appliances"},
    {"name": "Electric Food Processor", "price": 89.99, "description": "Chop, slice, and dice with ease.", "category": "Home Appliances"},
    {"name": "Smartwatch Charger", "price": 19.99, "description": "Keep your smartwatch charged and ready.", "category": "Accessories"},
    {"name": "Portable Air Purifier", "price": 59.99, "description": "Clean air wherever you go.", "category": "Health"},
    {"name": "Men's Running Shorts", "price": 29.99, "description": "Comfortable shorts for running.", "category": "Clothing"},
    {"name": "Women's Yoga Pants", "price": 39.99, "description": "Stylish and comfortable yoga pants.", "category": "Clothing"},
    {"name": "Kids' Educational Tablet", "price": 149.99, "description": "Fun and educational tablet for kids.", "category": "Electronics"},
    {"name": "Smartphone Car Mount", "price": 24.99, "description": "Securely mount your smartphone in your car.", "category": "Accessories"},
    {"name": "Electric Kettle with Temperature Control", "price": 49.99, "description": "Perfectly brew your tea or coffee.", "category": "Home Appliances"},
    {"name": "Wireless Home Speaker", "price": 99.99, "description": "Fill your home with music wirelessly.", "category": "Electronics"},
    {"name": "Smart Fitness Scale", "price": 49.99, "description": "Track your weight and body metrics.", "category": "Health"},
    {"name": "Men's Swim Trunks", "price": 34.99, "description": "Stylish swim trunks for summer.", "category": "Clothing"},
    {"name": "Women's Sports Bra", "price": 29.99, "description": "Comfortable and supportive sports bra.", "category": "Clothing"},
    {"name": "Kids' Art Supplies Set", "price": 19.99, "description": "Everything your child needs to create art.", "category": "Toys"},
    {"name": "Smartphone Photography Kit", "price": 39.99, "description": "Enhance your smartphone photography skills.", "category": "Accessories"},
    {"name": "Electric Griddle", "price": 59.99, "description": "Cook breakfast for the whole family.", "category": "Home Appliances"},
    {"name": "Portable Water Filter", "price": 29.99, "description": "Stay hydrated with clean water anywhere.", "category": "Outdoor"},
    {"name": "Camping Hammock", "price": 39.99, "description": "Relax in comfort while camping.", "category": "Outdoor"},
    {"name": "Smartphone Screen Protector", "price": 14.99, "description": "Protect your smartphone screen from scratches.", "category": "Accessories"},
    {"name": "Electric Hot Pot", "price": 49.99, "description": "Cook delicious meals with this hot pot.", "category": "Home Appliances"},
    {"name": "Men's Leather Wallet", "price": 39.99, "description": "Stylish and durable leather wallet.", "category": "Accessories"},
    {"name": "Women's Tote Bag", "price": 49.99, "description": "Fashionable tote bag for everyday use.", "category": "Accessories"},
    {"name": "Kids' Building Blocks", "price": 29.99, "description": "Encourage creativity with building blocks.", "category": "Toys"},
    {"name": "Smartphone Tripod Stand", "price": 24.99, "description": "Stabilize your smartphone for photos and videos.", "category": "Accessories"},
    {"name": "Electric Food Steamer", "price": 39.99, "description": "Steam your food for healthier meals.", "category": "Home Appliances"},
    {"name": "Wireless Bluetooth Adapter", "price": 19.99, "description": "Add Bluetooth capability to your devices.", "category": "Electronics"},
    {"name": "Men's Hiking Boots", "price": 89.99, "description": "Durable boots for hiking adventures.", "category": "Footwear"},
    {"name": "Women's Winter Coat", "price": 129.99, "description": "Stay warm and stylish in winter.", "category": "Clothing"},
]

def populate_db():
    with app.app_context():
        for product in mock_products:
            new_product = Product(
                name=product["name"],
                price=product["price"],
                description=product["description"],
                category=product["category"]
            )
            db.session.add(new_product)
        db.session.commit()

if __name__ == "__main__":
    populate_db()

print("Mock e-commerce products added to the database.")
